version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    depends_on:
      - db
      - redis
  db:
    image: mcr.microsoft.com/mssql/server
  redis:
    image: redis