version: '3.4'

services:
  webapi:
    container_name: WebApi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MainDb__ConnectionString=Server=db; Database=BasicCmsDb; User=sa; Password=Change_me123!; MultipleActiveResultSets=true;
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5000:80"
    restart: on-failure

  db:
    container_name: db
    volumes:
      - db-data:/var/opt/mssql
    ports:
      - "1433:1433"
    environment:
      - "SA_PASSWORD=Change_me123!"
      - "ACCEPT_EULA=Y"

volumes:
  db-data: